server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: producer
          uri: ${PRODUCER_URI:http://localhost:8081}
          predicates:
            - Path=/producer/**
          filters:
            - StripPrefix=1
        - id: consumer
          uri: ${CONSUMER_URI:http://localhost:8082}
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
